[package]
authors = ["Andre Bogus <bogusandre@gmail.de>", "Joshua Landau <joshua@landau.ws>"]
description = "count occurrences of a byte in a byte slice, fast"
name = "bytecount"
version = "0.1.3"
license = "Apache-2.0/MIT"
repository = "https://github.com/llogiq/bytecount"

[dev-dependencies]
quickcheck = "0.3.1"
rand = "0.3.14"
