[package]
authors = ["Andre Bogus <bogusandre@gmail.de>", "Joshua Landau"]
description = "count occurrences of a byte in a byte slice, fast"
name = "bytecount"
version = "0.1.0"
license = "Apache 2/MIT"

[dev-dependencies]
quickcheck = "0.3.1"
rand = "0.3.14"
